jenkins:
plugins:
  required:
    - blueocean: latest
    - greenballs: latest
    - chucknorris: latest
    - icon-shim: latest
    - credentials: latest
    - matrix-auth: latest
    - script-security: latest
    - junit: latest
    - matrix-project: latest
    - cloudbees-folder: latest
    - config-file-provider: latest
    - managed-scripts: latest
    - job-dsl: latest
    - git-client: latest
    - scm-api: latest
    - git: latest
    - github-api: latest
    - ruby-runtime: latest
    - token-macro: latest
    - jquery: latest
    - jquery-ui: latest
    - rake: latest
    - plain-credentials: latest
    - ssh-agent: latest
    - analysis-core: latest
    - rvm: latest
    - mercurial: latest
    - bitbucket: latest
    - bitbucket-pullrequest-builder: latest
    - github: latest
    - ghprb: latest
    - jira: latest
    - confluence-publisher: latest
    - jenkins-cloudformation-plugin: latest
    - packer: latest
    - jackson2-api: latest
    - aws-java-sdk: latest
    - aws-credentials: latest
    - s3: latest
    - gravatar: latest
    - hipchat: latest
    - checkstyle: latest
    - disk-usage: latest
    - rubyMetrics: latest
    - build-pipeline-plugin: latest
    - copyartifact: latest
    - delivery-pipeline-plugin: latest
    - parameterized-trigger: latest
    - prereq-buildstep: latest
    - promoted-builds: latest
    - ssh: latest
    - node-iterator-api: latest
    - ec2: latest
    - git-parameter: latest
    - ansicolor: latest
    - embeddable-build-status: latest
    - buildgraph-view: latest
    - description-setter: latest
    - jquery-detached: latest
    - ace-editor: latest
    - workflow-cps: latest
    - groovy-postbuild: latest
    - gradle: latest
    - slack: latest
    - windows-slaves: latest
    - aws-lambda: latest
    - codedeploy: latest
    - mailer: latest
    - github-oauth: latest
    - ssh-credentials: latest
    - ssh-slaves: latest
    - durable-task: latest
    - docker-plugin: latest
    - git-server: latest
    - structs: latest
    - workflow-support: latest
    - pipeline-stage-step: latest
    - pipeline-stage-view: latest
    - workflow-cps-global-lib: latest
    - pipeline-input-step: latest
    - workflow-basic-steps: latest
    - workflow-multibranch: latest
    - workflow-scm-step: latest
    - workflow-job: latest
    - workflow-durable-task-step: latest
    - workflow-step-api: latest
    - pipeline-build-step: latest
    - workflow-api: latest
    - workflow-aggregator: latest
    - workflow-remote-loader: latest
    - docker-workflow: latest
    - credentials-binding: latest
    - envinject: latest
    - maven-plugin: latest
    - conditional-buildstep: latest
    - bouncycastle-api: latest
    - github-organization-folder: latest
    - github-branch-source: latest
    - branch-api: latest
    - pipeline-rest-api: latest
    - momentjs: latest
    - handlebars: latest
    - javadoc: latest
    - run-condition: latest
    - next-build-number: latest
    - multiple-scms: latest
    - cloudbees-bitbucket-branch-source: latest
